version: 0.1.{build}

image: Visual Studio 2017
platform:
  - x64

clone_folder: c:\projects\marktext

branches:
  only:
    - master
skip_tags: true

environment:
  GH_TOKEN:
    secure: Ki5AJWygDYhzMJxl0b0rDx3bhAYmar2aPdwVHiai9IigqsvZpWHLeI3qpTiiaOWL

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 $env:PLATFORM
  - choco install yarn --ignore-dependencies

  - node --version
  - npm --version
  - yarn --version

  - yarn

cache:
  - node_modules
  - '%LOCALAPPDATA%\electron\Cache'
  - '%LOCALAPPDATA%\electron-builder\cache'
  - '%LOCALAPPDATA%\Yarn\cache'

build_script:
  - yarn run lint
  - yarn run release:win

  # calculate checksums
  - ps: get-filehash -Algorithm SHA256 "build\Mark Text *.exe"
  - ps: get-filehash -Algorithm SHA256 "build\Mark Text Setup *.exe"

test: off
# test_script:
#   - yarn test